#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$DATABASE_USER" WITH PASSWORD '$DATABASE_PASSWORD';
    CREATE DATABASE "$DATABASE_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$DATABASE_USER" TO "$DATABASE_USER";
EOSQL