version: "3.7"

networks:
  docker-net:
    driver: bridge

services:
  nginx:
    restart: always
    image: nginx
    ports:
        - "80:80"
    hostname: nginx
    container_name: nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./rest_todo/resources/:/www/data/rest_todo/
      - ./sockets/:/sockets/
    networks:
        - docker-net
    depends_on:
      - rest_todo
    logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "5"

  db:
    image: postgres:12.2
    restart: always
    hostname: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init_user_db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - docker-net

  rest_todo:
    restart: unless-stopped
    build: ../
    container_name: rest_todo
    volumes:
      - ./rest_todo/:/data
      - ./sockets/:/sockets
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=postgres://$DATABASE_USER:$DATABASE_PASSWORD@db:5432/$DATABASE_USER
      - RESOURCES_DIR=/data/resources/
    depends_on:
      - db
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - docker-net
